const mongoose = require('mongoose');
const Schema = mongoose.Schema;

var NutrientValue = new Schema({
    name_en: String,
    name_vi: String,
    // note: String,
    // type: String,
    // weight: Number,
    // energyC: Number,
    // energeJ: Number,
    // protein: Number,
    // fat: Number,
    // carbohydrate: Number,
    // fiber: Number,
    // ash: Number,
    // totalSugar: Number,
    // calcium: Number,
    // iron: Number,
    // manganese: Number,
    // phosphorous: Number,
    // patassium: Number,
    // sodium: Number,
    // zinc: Number,
    // copper: Number,
    // selenium: Number,
    // vitaminC: Number,
    // vitaminB1: Number,
    // vitaminB2: Number,
    // vitaminPP: Number,
    // vitaminB5: Number,
    // vitaminB6: Number,
    // folate: Number,
    // vitaminB9: Number,
    // vitaminH: Number,
    // vitaminB12: Number,
    // vitaminA: Number,
    // vitaminD: Number,
    // vitaminE: Number,
    // vitaminK: Number,
    // betaCaroten: Number,
    // alphaCaronten: Number,
    // lycopen: Number,
    // totalIsoflavone: Number,
    // totalAcid: Number,
    // cholesterol: Number,
    // phytosterol: Number
});

module.exports = mongoose.model('nutrient_value', NutrientValue);